spring:
  profiles:
    active: dev
    #active: ${spring.profiles.active}
  application:
    name: ctmp01

---
#开发环境
# app
server:
    port: 8080

# spring
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    remote:
      secret: secret

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ctmp?characterEncoding=utf8

    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
# mongodb 配置
  data:
    mongodb:
      host: 192.168.148.251
      port: 27017
      database: ctmp02
      username: kobe
      password: rootkobe

debug: false

#logging DEBUG < INFO < WARN < ERROR < FATAL
logging:
  level:
    root: INFO
  file: ./logs/app-logging.log
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

---
#测试环境
# app
server:
    port: 8080

# spring
spring:
  profiles: test
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ctmp?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
  # REDIS (RedisProperties)
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    timeout: 0
  output:
    ansi:
      enabled: always
# mongodb 配置
  data:
    mongodb:
      host: 192.168.148.251
      port: 27017
      database: ctmp02
      username: kobe
      password: rootkobe

debug: false

#logging DEBUG < INFO < WARN < ERROR < FATAL
logging:
  level:
    root: INFO
  file: ./logs/app-logging.log
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml



---
# 线上环境
# app
server:
    port: 8081

# spring
spring:
  profiles: pro
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ctmp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
# mongodb 配置
  data:
    mongodb:
      host: 192.168.148.251
      port: 27017
      database: ctmp02
      username: kobe
      password: rootkobe

debug: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

