-- MySQL Script generated by MySQL Workbench
-- 09/29/17 17:54:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ctmp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ctmp` ;

-- -----------------------------------------------------
-- Schema ctmp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ctmp` DEFAULT CHARACTER SET utf8 ;
USE `ctmp` ;

-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_task_manage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_task_manage` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_task_manage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NULL COMMENT '任务名称',
  `priority` INT NULL COMMENT '优先级',
  `task_status` INT(1) NULL COMMENT '任务状态（1未执行，2执行中，3已完成，4已取消，5已终止）',
  `finish_time` VARCHAR(45) NULL COMMENT '完成时间',
  `task_require` VARCHAR(450) NULL COMMENT '任务要求',
  `test_explain` VARCHAR(450) NULL COMMENT '测试说明',
  `test_step` VARCHAR(45) NULL COMMENT '测试步骤',
  `case_description` VARCHAR(45) NULL COMMENT '用例描述',
  `update_person` VARCHAR(45) NULL COMMENT '最后更新人',
  `project_id` INT(1) NULL COMMENT '项目id',
  `email_notice` VARCHAR(45) NULL COMMENT '任务邮件通知',
  `execute_person` INT(20) NULL COMMENT '任务执行人',
  `create_person` VARCHAR(45) NULL COMMENT '创建人',
  `case_id` INT NULL COMMENT '用列id',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '任务管理表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_case_manage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_case_manage` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_case_manage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `case_name` VARCHAR(45) NULL COMMENT '用例名称',
  `case_id` INT NULL COMMENT '用例编号',
  `case_description` VARCHAR(450) NULL COMMENT '用例描述',
  `case_level` VARCHAR(45) NULL COMMENT '用例级别',
  `case_type` VARCHAR(45) NULL COMMENT '用例类型',
  `case_version` VARCHAR(45) NULL COMMENT '用例版本',
  `case_dir` INT NULL COMMENT '用列所在目录',
  `test_data` VARCHAR(450) NULL COMMENT '测试数据',
  `test_step` VARCHAR(450) NULL COMMENT '测试步骤',
  `test_explain` VARCHAR(45) NULL COMMENT '测试说明\n',
  `test_environment` VARCHAR(45) NULL COMMENT '测试环境',
  `test_result` INT(1) NULL COMMENT '测试结果(1未测试，2通过，3不通过，4阻塞)',
  `test_accessory` VARCHAR(45) NULL COMMENT '测试附件',
  `test_require` VARCHAR(45) NULL COMMENT '测试要求',
  `condition` VARCHAR(450) NULL COMMENT '预制条件',
  `expect_result` VARCHAR(450) NULL COMMENT '预期结果',
  `create_person` VARCHAR(45) NULL COMMENT '创建人',
  `belong_id` INT NULL COMMENT '所属人id',
  `product_id` VARCHAR(45) NULL COMMENT '产品id',
  `function` VARCHAR(45) NULL COMMENT '功能模块',
  `modify_person` VARCHAR(45) NULL COMMENT '修订人',
  `modify_description` VARCHAR(45) NULL COMMENT '修订描述',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `task_manage_id` INT NOT NULL COMMENT '关联任务管理表',
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_case_manage_t_migu_task_manage1_idx` (`task_manage_id` ASC),
  CONSTRAINT `fk_t_migu_case_manage_t_migu_task_manage1`
    FOREIGN KEY (`task_manage_id`)
    REFERENCES `ctmp`.`t_migu_task_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用例管理表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_case_task_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_case_task_template` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_case_task_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field_name` VARCHAR(45) NULL COMMENT '字段名',
  `field_type` INT(1) NULL COMMENT '字段类型(1文本框，2下拉框，3时间控件)',
  `field_content` VARCHAR(450) NULL COMMENT '字段内容',
  `priority` INT(1) NULL COMMENT '优先展示(1不优先，2优先)',
  `required` INT(1) NULL COMMENT '是否必填（1否，2是）',
  `type` INT(1) NULL COMMENT '类型（1用例，2任务）',
  `test_type_id` INT NULL COMMENT '测试类型id',
  `is_rows` INT NULL COMMENT '是否为记录行（0否，1是）',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `case_manage_id` INT NOT NULL COMMENT '关联用列管理表',
  `task_manage_id` INT NOT NULL COMMENT '关联任务管理表',
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_case_task_template_t_migu_case_manage1_idx` (`case_manage_id` ASC),
  INDEX `fk_t_migu_case_task_template_t_migu_task_manage1_idx` (`task_manage_id` ASC),
  CONSTRAINT `fk_t_migu_case_task_template_t_migu_case_manage1`
    FOREIGN KEY (`case_manage_id`)
    REFERENCES `ctmp`.`t_migu_case_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_migu_case_task_template_t_migu_task_manage1`
    FOREIGN KEY (`task_manage_id`)
    REFERENCES `ctmp`.`t_migu_task_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用例任务模板表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_email_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_email_setting` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_email_setting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receiver` VARCHAR(45) NULL COMMENT '收件人',
  `copyer` VARCHAR(450) NULL COMMENT '抄送人',
  `theme` VARCHAR(450) NULL COMMENT '主题',
  `list_name` VARCHAR(450) NULL COMMENT '列表名称',
  `test_type_id` INT NULL COMMENT '测试类型id',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '邮件设置表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_test_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_test_type` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_test_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL COMMENT '类型名称',
  `description` VARCHAR(450) NULL COMMENT '说明',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `task_manage_id` INT NOT NULL COMMENT '关联任务管理表',
  `case_manage_id` INT NOT NULL COMMENT '关联用列管理表',
  `case_task_template_id` INT NOT NULL COMMENT '关联用列任务模板表',
  `email_setting_id` INT NOT NULL COMMENT '关联邮件设置表',
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_test_type_t_migu_task_manage1_idx` (`task_manage_id` ASC),
  INDEX `fk_t_migu_test_type_t_migu_case_manage1_idx` (`case_manage_id` ASC),
  INDEX `fk_t_migu_test_type_t_migu_case_task_template1_idx` (`case_task_template_id` ASC),
  INDEX `fk_t_migu_test_type_t_migu_email_setting1_idx` (`email_setting_id` ASC),
  CONSTRAINT `fk_t_migu_test_type_t_migu_task_manage1`
    FOREIGN KEY (`task_manage_id`)
    REFERENCES `ctmp`.`t_migu_task_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_migu_test_type_t_migu_case_manage1`
    FOREIGN KEY (`case_manage_id`)
    REFERENCES `ctmp`.`t_migu_case_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_migu_test_type_t_migu_case_task_template1`
    FOREIGN KEY (`case_task_template_id`)
    REFERENCES `ctmp`.`t_migu_case_task_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_migu_test_type_t_migu_email_setting1`
    FOREIGN KEY (`email_setting_id`)
    REFERENCES `ctmp`.`t_migu_email_setting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '测试类型表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_channel_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_channel_template` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_channel_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '渠道名称',
  `address` VARCHAR(100) NULL COMMENT '渠道地址',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '渠道模板表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_report_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_report_template` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_report_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `list_id` VARCHAR(450) NULL COMMENT '邮件列表id',
  `email_history` VARCHAR(450) NULL COMMENT '邮件历史',
  `begin_time` VARBINARY(45) NULL COMMENT '开始时间',
  `end_time` VARCHAR(45) NULL COMMENT '结束时间',
  `user_id` INT NULL COMMENT '用户id',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `email_setting_id` INT NOT NULL COMMENT '关联邮件设置表',
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_report_template_t_migu_email_setting1_idx` (`email_setting_id` ASC),
  CONSTRAINT `fk_t_migu_report_template_t_migu_email_setting1`
    FOREIGN KEY (`email_setting_id`)
    REFERENCES `ctmp`.`t_migu_email_setting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '报告模板表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_dir_stair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_dir_stair` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_dir_stair` (
  `id` INT NOT NULL,
  `dir_name` VARCHAR(45) NULL COMMENT '目录名',
  `insert_date` VARCHAR(45) NULL,
  `update_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_dir_stair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_dir_stair` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_dir_stair` (
  `id` INT NOT NULL,
  `dir_name` VARCHAR(45) NULL COMMENT '目录名',
  `insert_date` VARCHAR(45) NULL,
  `update_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_dir_second`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_dir_second` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_dir_second` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dir_name` VARCHAR(45) NULL COMMENT '目录',
  `dir_id` VARCHAR(45) NULL COMMENT '一级目录id',
  `insert_date` VARCHAR(45) NULL,
  `update_date` VARCHAR(45) NULL,
  `t_migu_dir_stair_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_dir_second_t_migu_dir_stair1_idx` (`t_migu_dir_stair_id` ASC),
  CONSTRAINT `fk_t_migu_dir_second_t_migu_dir_stair1`
    FOREIGN KEY (`t_migu_dir_stair_id`)
    REFERENCES `ctmp`.`t_migu_dir_stair` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_history` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `report_id` INT NULL COMMENT '报道模板id',
  `record_content` VARCHAR(450) NULL COMMENT '记录内容',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `report_template_id` INT NOT NULL COMMENT '关联报告模板表',
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_history_t_migu_report_template1_idx` (`report_template_id` ASC),
  CONSTRAINT `fk_t_migu_history_t_migu_report_template1`
    FOREIGN KEY (`report_template_id`)
    REFERENCES `ctmp`.`t_migu_report_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '历史记录表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_case_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_case_record` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_case_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `change_person` VARCHAR(45) NULL COMMENT '变更人',
  `change_time` VARCHAR(45) NULL COMMENT '变更时间',
  `change_content` VARCHAR(450) NULL COMMENT '变更内容',
  `task_id` INT NULL COMMENT '任务id',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用列变更记录表';


-- -----------------------------------------------------
-- Table `ctmp`.`t_migu_group_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctmp`.`t_migu_group_people` ;

CREATE TABLE IF NOT EXISTS `ctmp`.`t_migu_group_people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NULL COMMENT '分组名称',
  `user_id` INT NULL COMMENT '成员id',
  `is_leader` INT(1) NULL COMMENT '是否是组长（1普通成员，2组长）',
  `insert_time` VARCHAR(45) NULL COMMENT '插入时间',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间\n',
  `task_manage_id` INT NOT NULL COMMENT '关联任务管理表',
  `case_manage_id` INT NOT NULL COMMENT '关联任务管理表',
  PRIMARY KEY (`id`),
  INDEX `fk_t_migu_group_people_t_migu_task_manage1_idx` (`task_manage_id` ASC),
  INDEX `fk_t_migu_group_people_t_migu_case_manage1_idx` (`case_manage_id` ASC),
  CONSTRAINT `fk_t_migu_group_people_t_migu_task_manage1`
    FOREIGN KEY (`task_manage_id`)
    REFERENCES `ctmp`.`t_migu_task_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_migu_group_people_t_migu_case_manage1`
    FOREIGN KEY (`case_manage_id`)
    REFERENCES `ctmp`.`t_migu_case_manage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
